name: Go CI

on:
  pull_request:

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
      - name: Build
        run: go build .
      - name: Fmt
        run: test -z $(gofmt -l .)
      - name: Vet
        run: go vet ./...
      - name: Lint
        uses: golangci/golangci-lint-action@v5
        with:
          version: v1.54
      - name: Test
        run: go test -v -race ./...
